# Generated by Django 2.1.2 on 2019-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('public', models.CharField(blank=True, max_length=20, null=True)),
                ('display', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('source', models.CharField(max_length=500)),
                ('img_url', models.CharField(blank=True, max_length=300, null=True)),
                ('view_page', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
