# Generated by Django 2.1.2 on 2018-11-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='public',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
