# Generated by Django 2.1.3 on 2019-01-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
        migrations.AddField(
            model_name='new',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='view_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='new',
            name='describe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='public',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
