# Generated by Django 2.0.5 on 2019-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190106_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='new',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
